[[menu.main]]
  name = "Test"
  identifier = "test"
  url = "/docs/test/"
  weight = 1

[[menu.main]]
  parent = "test"
  name = "Level 1a"
  identifier = "level1a"
  url = "/docs/test/level1a/"
  weight = 1

[[menu.main]]
  parent = "level1a"
  name = "Level 2a"
  identifier = "level2a"
  url = "/docs/test/level1a/level2a/"
  weight = 1

[[menu.main]]
  parent = "level2a"
  name = "Level 3a"
  identifier = "level3a"
  url = "/docs/test/level1a/level2a/level3a/"
  weight = 1

[[menu.main]]
  parent = "level2a"
  name = "Level 3b"
  identifier = "level3b"
  url = "/docs/test/level1a/level2a/level3b/"
  weight = 2

[[menu.main]]
  parent = "level1a"
  name = "Level 2b"
  identifier = "level2b"
  url = "/docs/test/level1a/level2b/"
  weight = 2

[[menu.main]]
  parent = "test"
  name = "Level 1b"
  identifier = "level1b"
  url = "/docs/test/level1b/"
  weight = 2
