# baseURL = "http://archiv.ilmenauer-schachverein.de"
languageCode = "de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
title = "ISV - Archiv"
theme = "hugo-book"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    [languages.de.params]
      pygmentsCodeFences = true
      pygmentsOptions = "linenos=table"
      pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
    tabWidth = 4

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/IlmenauerSchachverein/ISVArchiv"
  weight = 10

[[menu.after]]
  name = "Website"
  url = "https://ilmenauer-schachverein.de/"
  weight = 20
