baseURL = "http://archiv.ilmenauer-schachverein.de"
languageCode = "de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
title = "ISV - Archiv"
theme = "hugo-book"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    [languages.de.params]
      pygmentsCodeFences = true
      pygmentsOptions = "linenos=table"
      pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
    tabWidth = 4
 