baseURL = "http://archiv.ilmenauer-schachverein.de"
languageCode = "de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

theme = "hugo-book"

[languages.en.params]
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
    tabWidth = 4